CREATE TABLE IF NOT EXISTS FABRICANTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT);
CREATE TABLE IF NOT EXISTS ARTICULOS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, PRECIO INTEGER, FAB INTEGER, FOREIGN KEY(FAB) REFERENCES FABRICANTES(ID));
CREATE TABLE IF NOT EXISTS CLIENTES (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, DIRTECCION TEXT, TELEFONO INTEGER);
