CREATE TABLE IN NOT EXISTS FABRICANTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT);
CREATE TABLE IN NOT EXISTS ARTICULOS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, PRECIO INTEGER, FAB INTEGER, FOREIGN KEY(FAB) REFERENCES FABRICANTES(ID));
CREATE TABLE IN NOT EXISTS CLIENTES (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, DIRTECCION TEXT, TELEFONO INTEGER);
