BEGIN TRANSACTION;
CREATE TABLE FABRICANTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT);
INSERT INTO `FABRICANTES` (ID,NOMBRE) VALUES (1,'samsung');
CREATE TABLE ARTICULOS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, PRECIO INTEGER, FAB INTEGER, FOREIGN KEY(FAB) REFERENCES FABRICANTES(ID));
INSERT INTO `ARTICULOS` (ID,NOMBRE,PRECIO,FAB) VALUES (1,'mouse',90,'genius'),
COMMIT;
