import sqlite3

base = sqlite3.connect('pi2.db')
c = base.cursor()

c.execute("CREATE TABLE IF NOT EXISTS FABRICANTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT);")
base.commit()

c.execute("CREATE TABLE IF NOT EXISTS  ARTICULOS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, PRECIO INTEGER, FAB INTEGER, FOREIGN KEY(FAB) REFERENCES FABRICANTES(ID));")
c.execute("CREATE TABLE IF NOT EXISTS CLIENTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, CUIL INTEGER, DIRECCION TEXT, CP TEXT, TELEFONO INTEGER);")

base.commit()
