import sqlite3

base = sqlite3.connect('pi2.db')
c = base.cursor()

c.execute("CREATE TABLE FABRICANTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT);")
c.execute("CREATE TABLE ARTICULOS(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, PRECIO INTEGER, FAB INTEGER, FOREIGN KEY(FAB) REFERENCES FABRICANTES(ID));")
c.execute("CREATE TABLE CLIENTES(ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, CUIL INTEGER, DIRECCION TEXT, CP TEXT, TELEFONO INTEGER);")

base.commit()
